/// All translatable keys used across Dargak.
///
/// We keep translations in plain Dart maps (rather than generated ARB) so the
/// language can be toggled instantly at runtime with zero rebuild/codegen step,
/// and so an Egyptian-dialect reviewer can edit copy in one place.
class AppStrings {
  AppStrings._();

  static const Map<String, String> en = {
    'app_name': 'Dargak',
    'app_tagline': 'Your shop, in your pocket',

    // Navigation
    'nav_home': 'Home',
    'nav_ledger': 'Ledger',
    'nav_qr': 'Get Paid',
    'nav_debts': 'Debts',
    'nav_settings': 'Settings',

    // Dashboard
    'welcome_back': 'Welcome back',
    'net_profit': 'Net Profit',
    'total_revenue': 'Product Revenue',
    'stock_cost': 'Cost of Stock',
    'bills': 'Bills & Rent',
    'service_commission': 'Service Commission',
    'pure_money': 'Pure money you made',
    'today': 'Today',
    'this_week': 'This Week',
    'this_month': 'This Month',
    'product_turnover': 'Product Turnover',
    'service_revenue': 'Service Revenue',
    'quick_actions': 'Quick Actions',
    'recent_activity': 'Recent Activity',
    'see_all': 'See All',
    'no_activity': 'No entries yet. Add your first sale!',

    // Entities / actions
    'add_sale': 'Add Sale',
    'add_expense': 'Add Expense',
    'add_debt': 'Add Debt',
    'add_fawry': 'Fawry / Wallet',
    'sales': 'Sales',
    'expenses': 'Expenses',
    'debts': 'Debts',
    'fawry': 'Fawry & Wallet',

    // Sale form
    'sale_amount': 'Sale amount',
    'payment_method': 'Payment method',
    'cash': 'Cash',
    'instapay': 'InstaPay',
    'wallet': 'E-Wallet',
    'card': 'Card',
    'product_category': 'Product category',
    'quantity': 'Quantity',
    'neighborhood': 'Neighborhood / Area',
    'note_optional': 'Note (optional)',
    'save': 'Save',
    'saved': 'Saved successfully',

    // Categories
    'cat_vegetables': 'Vegetables & Fruit',
    'cat_groceries': 'Groceries',
    'cat_beverages': 'Beverages',
    'cat_dairy': 'Dairy',
    'cat_snacks': 'Snacks',
    'cat_cigarettes': 'Cigarettes',
    'cat_pharmacy': 'Pharmacy',
    'cat_other': 'Other',

    // Expense form
    'expense_amount': 'Expense amount',
    'expense_type': 'Expense type',
    'exp_stock': 'Wholesale Stock',
    'exp_rent': 'Rent',
    'exp_electricity': 'Electricity',
    'exp_supplier': 'Supplier Payment',
    'exp_salaries': 'Salaries',
    'exp_other': 'Other',
    'supplier_name': 'Supplier name (optional)',

    // Debts
    'debt_owed_to_me': 'He owes me',
    'debt_i_owe': 'I owe them',
    'contact_name': 'Name',
    'phone_number': 'Phone number',
    'pick_from_contacts': 'Pick from contacts',
    'debt_amount': 'Amount',
    'due_date': 'Due date (optional)',
    'mark_settled': 'Mark as settled',
    'settled': 'Settled',
    'total_owed_to_me': 'They owe you',
    'total_i_owe': 'You owe',
    'send_reminder': 'Send reminder',
    'no_debts': 'No open debts. Everyone paid up!',

    // Fawry / wallet tracker
    'fawry_title': 'Fawry & Wallet Service',
    'fawry_hint':
        'Log bill payments & recharges you did for a customer, and track your commission.',
    'reference_number': 'Reference / transaction no.',
    'customer_phone': 'Customer mobile',
    'gross_amount': 'Transaction value',
    'merchant_commission': 'Your commission (profit)',
    'service_type': 'Service type',
    'svc_bill': 'Bill payment',
    'svc_recharge': 'Mobile recharge',
    'svc_ewallet': 'E-wallet cash in/out',
    'svc_internet': 'Internet / ADSL',
    'svc_gov': 'Government fees',
    'svc_other': 'Other service',
    'total_commission': 'Total commission earned',

    // QR / Get paid
    'get_paid_title': 'Get Paid',
    'get_paid_sub': 'Show this QR — the customer scans & pays instantly',
    'amount_to_receive': 'Amount to receive',
    'payment_target': 'Receive to',
    'ipa_address': 'InstaPay address (name@instapay)',
    'wallet_number': 'Mobile wallet number',
    'generate_qr': 'Generate Payment QR',
    'share_whatsapp': 'Send on WhatsApp',
    'copy_link': 'Copy payment link',
    'copy_text': 'Copy transfer text',
    'copied': 'Copied to clipboard',
    'set_payment_info': 'Set your payment details first in Settings',
    'scan_to_pay': 'Scan to pay',

    // Settings
    'settings': 'Settings',
    'language': 'Language',
    'arabic': 'العربية',
    'english': 'English',
    'merchant_profile': 'Merchant Profile',
    'shop_name': 'Shop name',
    'owner_name': 'Owner name',
    'payment_details': 'Payment Details',
    'theme': 'Appearance',
    'theme_system': 'System',
    'theme_light': 'Light',
    'theme_dark': 'Dark',
    'export_pdf': 'Export monthly PDF report',
    'premium': 'Premium',
    'restore_purchase': 'Restore purchase',
    'about': 'About Dargak',
    'version': 'Version',
    'data_privacy': 'Data & Privacy',

    // Paywall
    'paywall_title': 'Unlock Dargak Pro',
    'paywall_sub': 'Grow without limits',
    'paywall_reason_customers':
        'You have reached the free limit of 40 customers.',
    'paywall_reason_pdf': 'PDF financial reports are a Pro feature.',
    'feat_unlimited_customers': 'Unlimited customers & debts',
    'feat_pdf': 'Clean monthly PDF reports',
    'feat_backup': 'Cloud backup & multi-device',
    'feat_insights': 'Advanced profit insights',
    'price_per_month': 'EGP {price} / month',
    'pay_fawry': 'Pay with Fawry link',
    'pay_vodafone': 'Pay with Vodafone Cash',
    'maybe_later': 'Maybe later',
    'most_popular': 'Most popular',

    // Common
    'cancel': 'Cancel',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'required': 'Required',
    'invalid_amount': 'Enter a valid amount',
    'currency': 'EGP',
    'delete_confirm': 'Delete this entry?',
    'no_whatsapp': 'WhatsApp is not installed',
  };

  static const Map<String, String> ar = {
    'app_name': 'درجك',
    'app_tagline': 'محلك في جيبك',

    // Navigation
    'nav_home': 'الرئيسية',
    'nav_ledger': 'الدفتر',
    'nav_qr': 'اقبض',
    'nav_debts': 'الديون',
    'nav_settings': 'الإعدادات',

    // Dashboard
    'welcome_back': 'أهلاً بيك',
    'net_profit': 'صافي الربح',
    'total_revenue': 'مبيعات البضاعة',
    'stock_cost': 'تكلفة البضاعة',
    'bills': 'فواتير وإيجار',
    'service_commission': 'عمولة الخدمات',
    'pure_money': 'الفلوس الصافية اللي كسبتها',
    'today': 'النهاردة',
    'this_week': 'الأسبوع',
    'this_month': 'الشهر',
    'product_turnover': 'حركة البضاعة',
    'service_revenue': 'إيراد الخدمات',
    'quick_actions': 'إجراءات سريعة',
    'recent_activity': 'آخر الحركات',
    'see_all': 'شوف الكل',
    'no_activity': 'لسه مفيش حركات. سجّل أول بيعة!',

    // Entities / actions
    'add_sale': 'إضافة بيعة',
    'add_expense': 'إضافة مصروف',
    'add_debt': 'إضافة دين',
    'add_fawry': 'فوري / محفظة',
    'sales': 'المبيعات',
    'expenses': 'المصاريف',
    'debts': 'الديون',
    'fawry': 'فوري والمحافظ',

    // Sale form
    'sale_amount': 'قيمة البيعة',
    'payment_method': 'طريقة الدفع',
    'cash': 'كاش',
    'instapay': 'إنستاباي',
    'wallet': 'محفظة إلكترونية',
    'card': 'كارت',
    'product_category': 'نوع المنتج',
    'quantity': 'الكمية',
    'neighborhood': 'المنطقة / الحي',
    'note_optional': 'ملاحظة (اختياري)',
    'save': 'حفظ',
    'saved': 'اتحفظ بنجاح',

    // Categories
    'cat_vegetables': 'خضار وفاكهة',
    'cat_groceries': 'بقالة',
    'cat_beverages': 'مشروبات',
    'cat_dairy': 'ألبان',
    'cat_snacks': 'سناكس',
    'cat_cigarettes': 'سجائر',
    'cat_pharmacy': 'صيدلية',
    'cat_other': 'أخرى',

    // Expense form
    'expense_amount': 'قيمة المصروف',
    'expense_type': 'نوع المصروف',
    'exp_stock': 'بضاعة جملة',
    'exp_rent': 'إيجار',
    'exp_electricity': 'كهرباء',
    'exp_supplier': 'دفعة مورّد',
    'exp_salaries': 'مرتبات',
    'exp_other': 'أخرى',
    'supplier_name': 'اسم المورّد (اختياري)',

    // Debts
    'debt_owed_to_me': 'عليه',
    'debt_i_owe': 'ليه',
    'contact_name': 'الاسم',
    'phone_number': 'رقم التليفون',
    'pick_from_contacts': 'اختار من جهات الاتصال',
    'debt_amount': 'المبلغ',
    'due_date': 'تاريخ الاستحقاق (اختياري)',
    'mark_settled': 'تحديد كمسدّد',
    'settled': 'اتسدد',
    'total_owed_to_me': 'ليك عند الناس',
    'total_i_owe': 'عليك للناس',
    'send_reminder': 'ابعت تذكير',
    'no_debts': 'مفيش ديون مفتوحة. الكل سدّد!',

    // Fawry / wallet tracker
    'fawry_title': 'خدمة فوري والمحافظ',
    'fawry_hint':
        'سجّل دفع الفواتير والشحن اللي عملته للزبون، وتابع عمولتك.',
    'reference_number': 'رقم العملية / المرجع',
    'customer_phone': 'موبايل الزبون',
    'gross_amount': 'قيمة العملية',
    'merchant_commission': 'عمولتك (الربح)',
    'service_type': 'نوع الخدمة',
    'svc_bill': 'دفع فاتورة',
    'svc_recharge': 'شحن رصيد',
    'svc_ewallet': 'إيداع/سحب محفظة',
    'svc_internet': 'إنترنت / ADSL',
    'svc_gov': 'رسوم حكومية',
    'svc_other': 'خدمة أخرى',
    'total_commission': 'إجمالي العمولة',

    // QR / Get paid
    'get_paid_title': 'اقبض فلوسك',
    'get_paid_sub': 'وريه الكود — الزبون يمسح ويدفع فوراً',
    'amount_to_receive': 'المبلغ المطلوب',
    'payment_target': 'استلام على',
    'ipa_address': 'عنوان إنستاباي (name@instapay)',
    'wallet_number': 'رقم المحفظة',
    'generate_qr': 'إنشاء كود الدفع',
    'share_whatsapp': 'إرسال على واتساب',
    'copy_link': 'نسخ رابط الدفع',
    'copy_text': 'نسخ نص التحويل',
    'copied': 'اتنسخ',
    'set_payment_info': 'ظبّط بيانات الدفع الأول من الإعدادات',
    'scan_to_pay': 'امسح للدفع',

    // Settings
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'arabic': 'العربية',
    'english': 'English',
    'merchant_profile': 'بيانات المحل',
    'shop_name': 'اسم المحل',
    'owner_name': 'اسم صاحب المحل',
    'payment_details': 'بيانات الدفع',
    'theme': 'المظهر',
    'theme_system': 'النظام',
    'theme_light': 'فاتح',
    'theme_dark': 'داكن',
    'export_pdf': 'تصدير تقرير شهري PDF',
    'premium': 'النسخة المدفوعة',
    'restore_purchase': 'استرجاع الاشتراك',
    'about': 'عن درجك',
    'version': 'الإصدار',
    'data_privacy': 'البيانات والخصوصية',

    // Paywall
    'paywall_title': 'افتح درجك برو',
    'paywall_sub': 'اكبر من غير حدود',
    'paywall_reason_customers': 'وصلت للحد المجاني وهو 40 عميل.',
    'paywall_reason_pdf': 'تقارير الـ PDF ميزة في النسخة برو.',
    'feat_unlimited_customers': 'عملاء وديون بلا حدود',
    'feat_pdf': 'تقارير شهرية PDF أنيقة',
    'feat_backup': 'نسخة احتياطية سحابية وأجهزة متعددة',
    'feat_insights': 'تحليلات أرباح متقدمة',
    'price_per_month': '{price} جنيه / شهرياً',
    'pay_fawry': 'ادفع برابط فوري',
    'pay_vodafone': 'ادفع بفودافون كاش',
    'maybe_later': 'بعدين',
    'most_popular': 'الأكثر اختياراً',

    // Common
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'confirm': 'تأكيد',
    'required': 'مطلوب',
    'invalid_amount': 'اكتب مبلغ صحيح',
    'currency': 'جنيه',
    'delete_confirm': 'تحذف الحركة دي؟',
    'no_whatsapp': 'واتساب مش متثبت',
  };
}
